# Site
name: 'The Reason For Being'
description: 'An online portfolio and source of information about Monica Reason.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'monicareason393@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    monica:
      name:           Monica
      site:           https://monicareason.github.io/
      avatar:         assets/images/avatar_monica.jpg
      bio:            "Hey I'm Monica! I started this blog as a way to showcase not only my marketing consulting portfolio but also my passion for food and travel. In my spare time, I try to contribute to various marketing (particularly product marketing) engagements and research new trends in the market, so this is a space for me to showcase my portfolio and thought leadership pieces on emerging trends of interest. I also hope to use this space to share my love of travel and food with the world. Being a  planner, my friends and family know they can rely on me for the best travel itineraries, tips, and tricks. My friends and family also rely on me for amazing food as I love to immerse myself in the kitchen, experimenting with different cooking and baking methods. I hope you enjoy my content and thank you for visiting!"
      email:          monicareason393@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: monica
      avatar: assets/images/avatar_monica.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, vendor]
